[package]
name = "dotweb"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"


[dependencies]
bytes = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
warp = "0.3"
